services:
  videogen:
    build: .
    container_name: videogen_studio
    ports:
      - "7860:7860"
    volumes:
      - ./projects:/app/projects
    env_file:
      - .env
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
    restart: unless-stopped
    networks:
      - local

networks:
  local:
    external: true
